---
# file: roles/k3s-workers/tasks/main.yml

- name: Download K3s installer script
  ansible.builtin.get_url:
    url: https://get.k3s.io
    dest: /tmp/install-k3s.sh
    mode: "0755"

- name: Install K3s
  ansible.builtin.shell: /tmp/install-k3s.sh

- name: Join K3s cluster
  ansible.builtin.shell: |-
    TOKEN="{{ hostvars['k3s-master']['cluster_token'].stdout }}"
    MASTER_IP="{{ hostvars['k3s-master']['ansible_default_ipv4']['address'] }}"
    /usr/local/bin/k3s agent --server https://{{ MASTER_IP }}:6443 --token ${TOKEN}
