---
# file: production/hosts

all:
  children:
    k3s-master:
    k3s-workers:

k3s-master:
  hosts:
    k3s-master1:
      ansible_host: 192.168.1.100

k3s-workers:
  hosts:
    k3s-worker1:
      ansible_host: 192.168.1.101
    k3s-worker2:
      ansible_host: 192.168.1.102
