---
# file: production/hosts

k3s-master:
  hosts:
    k3s-master1:
      ansible_host: 192.168.1.100
      ansible_fqdn: k3s-master1.lab.local

k3s-workers:
  hosts:
    k3s-worker1:
      ansible_host: 192.168.1.101
      ansible_fqdn: k3s-worker1.lab.local

k3s-cluster:
  children:
    k3s-master:
    k3s-workers:

all:
  children:
    k3s-master:
    k3s-workers:
