---
# file: ansible/roles/systembase/tasks/hardening.yaml
# references: https://docs.k3s.io/security/hardening-guide, CIS for Debian 11 and experience

- name: (sys) HARDENING | be sure needed packages are installed
  ansible.builtin.apt:
    install-recommends: false
    name: "{{ item }}"
    state: present
    update-cache: true
  loop:
    - ufw

- name: (sys) HARDENING | enable SSH key-based authentication for root
  ansible.posix.authorized_key:
    user: root
    key: "{{ lookup('file', '~/.ssh/id_ed25519.pub') }}"

- name: (sys) HARDENING | enable SSH key-based authentication
  ansible.posix.authorized_key:
    user: "{{ ssh_username }}"
    key: "{{ lookup('file', '/$HOME/.ssh/id_ed25519.pub') }}"

- name: (sys) HARDENING | restrict SSH access to specific users
  ansible.builtin.lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^AllowUsers'
    line: 'AllowUsers "{{ ssh_username }}"'
  notify: restart sshd

- name: (sys) HARDENING | disable unused network protocols
  ansible.builtin.copy:
    dest: /etc/modprobe.d/disable-protocols.conf
    content: |
      # Disable unused network protocols
      install dccp /bin/true
      install sctp /bin/true
      install rds /bin/true
      install tipc /bin/true
    mode: u=rw,g=r,o=r

# UFW
- name: UFW - allow all access from RFC1918 networks to this host
  community.general.ufw:
    rule: allow
    src: '{{ item }}'
  loop:
    - 10.0.0.0/8
    - 172.16.0.0/12
    - 192.168.0.0/16
  notify: reload ufw

- name: UFW - allow SSH
  community.general.ufw:
    rule: allow
    port: ssh
    proto: tcp
  notify: reload ufw

# - name: UFW - allow K3s traffic from specific IP addresses
#   community.general.ufw:
#     rule: allow
#     src: "{{ lookup('env', 'network_ip') }}"
#     to_port: 6443
#     proto: tcp
#     comment: 'Allow K3s traffic from specific IP address'
#   notify: reload ufw

# - name: UFW - allow K3s metrics-server
#   community.general.ufw:
#     rule: allow
#     src: "{{ lookup('env', 'network_ip') }}"
#     to_port: 10250
#     proto: tcp
#     comment: 'k3s metrics-server'
#   notify: reload ufw

# - name: UFW - allow K3s API server
#   community.general.ufw:
#     rule: allow
#     src: '10.42.0.0/16'
#     to_port: 6443
#     proto: tcp
#     comment: 'K3s API server'
#   notify: reload ufw

# - name: UFW - allow traffic on K3s network interfaces
#   community.general.ufw:
#     rule: allow
#     interface_in: "{{ item }}"
#     comment: "K3s {{ item }} network interface"
#   loop:
#     - 'cni0'
#     - 'flannel.1'
#     - 'kube-bridge'
#   notify: reload ufw

- name: UFW - enable UFW
  community.general.ufw:
    state: enabled
  register: ufw_enabled
  changed_when: ufw_enabled.changed
