---
# file: roles/systembase/tasks/main.yml

- name: Include NTP configuration
  ansible.builtin.import_tasks: ntp.yaml
  tags: ntp

- name: Include needed packages
  ansible.builtin.import_tasks: packages.yaml
  tags: packages

- name: Include sshd configuration
  ansible.builtin.import_tasks: sshd.yaml
  tags: sshd
