---
# file: roles/systembase/tasks/sshd.yml

- name: (ssh) ensure SSH daemon is enabled and running
  ansible.builtin.service:
    enabled: true
    name: "sshd"
    state: started

- name: (ssh) copy template file in destination
  ansible.builtin.template:
    src: sshd_config.j2
    dest: /etc/ssh/sshd_config
    mode: u=rw,g=r,o=r

- name: (ssh) validate ssh configuration
  ansible.builtin.command: '/usr/sbin/sshd -t'
  notify: restart sshd
  register: ssh_validated
  changed_when: ssh_validated.rc != 0
