---
# file: ansible/roles/systembase/tasks/sshd.yaml

- name: (sys) SSH | ensure SSH daemon is enabled and running
  ansible.builtin.service:
    enabled: true
    name: sshd
    state: started

- name: (sys) SSH | copy template file in destination
  ansible.builtin.template:
    src: sshd_config.j2
    dest: /etc/ssh/sshd_config
    mode: u=rw,g=r,o=r
  register: sshd_config_changed
  changed_when: false

- name: (sys) SSH | add SSH banner
  ansible.builtin.template:
    src: sshd_banner.j2
    dest: /etc/ssh/sshd_banner
    mode: u=rw,g=r,o=r
  register: sshd_banner_changed

- name: (sys) SSH | validate ssh configuration
  ansible.builtin.command: '/usr/sbin/sshd -t'
  register: ssh_validated
  changed_when: false

- name: (sys) SSH | restart sshd
  ansible.builtin.systemd:
    name: sshd
    state: restarted
  when: sshd_config_changed.changed or sshd_banner_changed.changed or ssh_validated.rc != 0
  changed_when: false

- name: (sys) SSH | comment out pam_motd.so line in /etc/pam.d/sshd
  ansible.builtin.lineinfile:
    path: /etc/pam.d/sshd
    regex: '^session\s+optional\s+pam_motd\.so.*'
    line: 'pam_motd.so'
    state: present
  changed_when: false
