---
# file: ansible/roles/systembase/system.yaml

- name: (sys) | be sure needed packages are installed
  ansible.builtin.apt:
    install-recommends: false
    name: "{{ item }}"
    state: present
    update-cache: true
  loop:
    - bash-completion
    - curl
    - htop
    - jq
    - logrotate
    - python3-kubernetes
    - qemu-guest-agent
    - rsync
    - strace
    - sudo
    - wireguard

- name: (sys) | set hostname
  ansible.builtin.hostname:
    name: "{{ inventory_hostname }}"

- name: (sys) | add user in sudo group
  ansible.builtin.user:
    name: "{{ lookup('env', 'ssh_username') }}"
    groups: sudo
    append: true

- name: (ansible) read /etc/hosts file
  ansible.builtin.slurp:
    path: /etc/hosts
  register: hosts_file

- name: (sys) | update /etc/hosts
  ansible.builtin.replace:
    path: /etc/hosts
    regexp: '^127\.0\.1\.1\s+.*$'
    replace: '127.0.1.1 {{ inventory_hostname }}'
    backup: true
  when: "'127.0.1.1' in hosts_file.content | b64decode"

- name: (ansible) retrieve inventory IP addresses and hostnames
  ansible.builtin.set_fact:
    inventory_entries: "{{ inventory_entries | default({}) | combine({hostvars[item].ansible_host: item}) }}"
  loop: "{{ groups['all'] }}"

- name: (sys) | update /etc/hosts with IP and hostname
  ansible.builtin.blockinfile:
    path: /etc/hosts
    block: |
      {% for ip, hostname in inventory_entries.items() %}
      {{ ip }} {{ hostname }}
      {% endfor %}


- name: (sys) | enable IPv4 forwarding
  ansible.posix.sysctl:
    name: net.ipv4.ip_forward
    value: "1"
    state: present
    reload: true

- name: (sys) | enable IPv6 forwarding
  ansible.posix.sysctl:
    name: net.ipv6.conf.all.forwarding
    value: "1"
    state: present
    reload: true

- name: (sys) | copy better bashrc file for user
  ansible.builtin.template:
    src: bashrc.j2
    dest: /home/{{ lookup('env', 'ssh_username') }}/.bashrc
    mode: "u=rw,g=r,o=r"

- name: (sys) | copy better bashrc file for root
  ansible.builtin.template:
    src: bashrc.j2
    dest: /root/.bashrc
    mode: "u=rw,g=r,o=r"
