---
# file: roles/k3s/tasks/check_install.yml

- name: Searching for K3s Installation
  ansible.builtin.command: which k3s
  changed_when: false
  ignore_errors: true
  register: k3s_check

- name: Check K3s Installation
  ansible.builtin.fail:
    msg: "K3s is not installed"
  when: k3s_check.rc != 0
  ignore_errors: true
  register: k3s_check_results

- name: Store Result in Variable
  ansible.builtin.set_fact:
    k3s_installation_status: "{{ k3s_installation_status | default({}) | combine({ansible_host: k3s_check.rc == 0}) }}"

- name: Display Installation Status
  ansible.builtin.debug:
    var: k3s_installation_status
