---
# file: roles/k3s/tasks/check_install.yml

- name: Searching for K3s Installation
  ansible.builtin.command: which k3s
  register: k3s_check
  changed_when: false
  ignore_errors: true
  check_mode: false

- name: Check k3s Installation
  ansible.builtin.debug:
    msg: "K3s is {{ 'installed' if k3s_check.rc == 0 else 'not installed' }}"
  failed_when: k3s_check.rc != 0
  ignore_errors: true
  register: k3s_check_results

- name: Store result in variable
  ansible.builtin.set_fact:
    k3s_installation_status: "{{ k3s_installation_status | default({}) | combine({ansible_host: k3s_check.rc == 0}) }}"

- name: Display installation status
  ansible.builtin.debug:
    var: k3s_installation_status
