---
# file: ansible/roles/k3s/tasks/install_workers.yaml

- name: K3s_install_workers | get the cluster node-token
  delegate_to: k3s-master1
  ansible.builtin.command: cat /var/lib/rancher/k3s/server/node-token
  register: token_output
  changed_when: token_output.rc != 0

- name: K3s_install_workers | create an ansible variable with the cluster node-token
  ansible.builtin.set_fact:
    k3s_cluster_token: "{{ token_output.stdout }}"

- name: K3s_install_workers | install k3s in agent mode with the node-token
  ansible.builtin.shell: curl -sfL https://get.k3s.io | INSTALL_K3S_EXEC='agent' K3S_URL=https://{{ hostvars['k3s-master1'].ansible_host }}:6443 K3S_TOKEN={{ k3s_cluster_token }} sh -
  register: k3sagent_install
  changed_when: k3sagent_install.rc != 0

- name: K3s_install_workers | check node status
  delegate_to: k3s-master1
  ansible.builtin.command: kubectl get node {{ inventory_hostname }}
  register: node_status
  check_mode: false
  changed_when: false
  async: 15
  poll: 0
