---
# file: ansible/roles/k3s/tasks/install_cilium.yaml

- name: Get Cilium CLI version
  ansible.builtin.shell: curl -s https://raw.githubusercontent.com/cilium/cilium-cli/main/stable.txt
  register: cilium_cli_version

- name: Set Cilium CLI variables
  ansible.builtin.set_fact:
    goos: "{{ ansible_system | lower }}"
    goarch: "{{ 'amd64' if ansible_architecture == 'x86_64' else 'arm64' }}"
    cilium_cli_version: "{{ cilium_cli_version.stdout | trim }}"

- name: Download Cilium CLI tarball and checksum
  ansible.builtin.get_url:
    url: "https://github.com/cilium/cilium-cli/releases/download/{{ cilium_cli_version }}/cilium-{{ goos }}-{{ goarch }}.tar.gz"
    dest: "/tmp/cilium-{{ goos }}-{{ goarch }}.tar.gz"
  register: cilium_tarball

- name: Download Cilium CLI checksum
  ansible.builtin.get_url:
    url: "https://github.com/cilium/cilium-cli/releases/download/{{ cilium_cli_version }}/cilium-{{ goos }}-{{ goarch }}.tar.gz.sha256sum"
    dest: "/tmp/cilium-{{ goos }}-{{ goarch }}.tar.gz.sha256sum"
  register: cilium_checksum

- name: Verify Cilium CLI tarball checksum
  ansible.builtin.shell: "sha256sum -c /tmp/cilium-{{ goos }}-{{ goarch }}.tar.gz.sha256sum"
  args:
    chdir: "/tmp"
  register: checksum_result
  changed_when: false

- name: Extract Cilium CLI tarball
  ansible.builtin.unarchive:
    src: "/tmp/cilium-{{ goos }}-{{ goarch }}.tar.gz"
    dest: /usr/local/bin
    remote_src: true
    creates: "/usr/local/bin/cilium"
  when: checksum_result.rc == 0

- name: Clean up Cilium CLI tarball and checksum
  ansible.builtin.file:
    path: "/tmp/cilium-{{ goos }}-{{ goarch }}.tar.gz"
    state: absent
  when: checksum_result.rc == 0

- name: Clean up Cilium CLI checksum
  ansible.builtin.file:
    path: "/tmp/cilium-{{ goos }}-{{ goarch }}.tar.gz.sha256sum"
    state: absent
  when: checksum_result.rc == 0

- name: Install Cilium chart
  environment:
    KUBECONFIG: "/etc/rancher/k3s/k3s.yaml"
  kubernetes.core.helm:
    release_name: cilium
    chart_ref: cilium
    chart_version: "1.14.0"
    chart_repo_url: https://helm.cilium.io/
    release_namespace: kube-system
    create_namespace: false
    values:
      kubeProxyReplacement: strict
      k8sServiceHost: "{{ hostvars['k3s-master1'].ansible_host }}"
      k8sServicePort: 6443
      ipam:
        mode: "cluster-pool"
        operator:
          clusterPoolIPv4PodCIDRList:
            - "10.42.0.0/16"
