---
# file: ansible/roles/k3s-master/tasks/main.yaml

- name: Purge the registered variable
  become: false
  ansible.builtin.set_fact:
    k3s_installation_status: null

- name: Include check k3s install
  become: false
  ansible.builtin.import_tasks: check_install.yaml
  tags: k3s-check

- name: Include k3s master install
  ansible.builtin.import_tasks: install_master.yaml
  when: "'k3s-master' in group_names and not k3s_installation_status[ansible_host]"
  tags: k3s-master

- name: Include helm installation
  ansible.builtin.import_tasks: install_helm.yaml
  when: "'k3s-master' in group_names"
  tags: helm

- name: Include k3s workers install
  ansible.builtin.import_tasks: install_workers.yaml
  when: "'k3s-workers' in group_names and not k3s_installation_status[ansible_host]"
  tags: k3s-workers

- name: Include k3s destroyer
  ansible.builtin.import_tasks: destroy.yaml
  tags: k3s-destroy
  when: "'k3s-destroy' in ansible_run_tags"

- name: Include kubernetes dashboard
  become: false
  ansible.builtin.import_tasks: dashboard.yaml
  when:
    - "'k3s-dashboard' in ansible_run_tags"
    - "'k3s-master' in group_names"
  tags: k3s-dashboard
