---
dependency:
  name: galaxy

driver:
  name: docker

platforms:
  - name: molecule-systembase
    image: "geerlingguy/docker-debian12-ansible:latest"
    command: ""
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    cgroupns_mode: host
    privileged: true
    pre_build_image: true

provisioner:
  name: ansible
  config_options:
    defaults:
      interpreter_python: auto_silent
      callback_whitelist: profile_tasks, timer, yaml
    ssh_connection:
      pipelining: false
  inventory:
    host_vars:
      molecule-systembase:
        ansible_fqdn: "molecule-systembase.lab.local"
        inventory_hostname: "molecule-systembase"
        ssh_username: "molecule"

scenario:
  name: default
  test_sequence:
    - dependency
    - cleanup
    - destroy
    - syntax
    - create
    - prepare
    - converge
    - idempotence
    - side_effect
    #- verify
    - cleanup
    - destroy
