---

- name: Prepare
  hosts: all
  become: true
  tasks:
    - name: Update host apt cache
      ansible.builtin.apt:
        update_cache: true
        cache_valid_time: 3600

    - name: Install python3-minimal for ansible
      ansible.builtin.shell: "test -e /usr/bin/python3 || (apt update -y && apt install python3-minimal --no-install-recommends)"
      changed_when: false

    - name: Get IP address of the connected Ethernet interface
      ansible.builtin.shell: "ip addr show dev eth0 | grep 'inet ' | awk '{print $2}' | cut -d/ -f1"
      register: ip_address
      changed_when: false

    - name: Set ansible_host to the retrieved IP address
      ansible.builtin.set_fact:
        ansible_host: "{{ ip_address.stdout }}"
