---
- name: Check K3s Installation
  ansible.builtin.command: which k3s
  register: k3s_check
  changed_when: false
  ignore_errors: true

- name: Check k3s Installation
  ansible.builtin.debug:
    msg: "K3s is {{ 'installed' if k3s_check.rc == 0 else 'not installed' }}"
