---

- name: Download K3s installer script
  ansible.builtin.get_url:
    url: https://get.k3s.io
    dest: /tmp/install-k3s.sh
    mode: "0755"

- name: Install K3s
  ansible.builtin.command: /tmp/install-k3s.sh

- name: Restart K3s service
  ansible.builtin.service:
    name: k3s
    state: restarted
  when: not ansible_check_mode
