---
# file: roles/k3s-master/tasks/main.yml

- name: Include check k3s install
  ansible.builtin.import_tasks: check_install.yaml
  tags: k3s-master

- name: Include k3s install
  ansible.builtin.import_tasks: install.yaml
  when: k3s_check.rc != 0
  tags: k3s-master
