---
# file: ansible/roles/systembase/handlers/main.yaml

- name: restart sshd
  ansible.builtin.service:
    name: sshd
    state: restarted

- name: restart systemd-timesyncd
  ansible.builtin.service:
    name: systemd-timesyncd
    state: restarted

- name: reload ufw
  community.general.ufw:
    state: reloaded

- name: Restart fail2ban
  ansible.builtin.service:
    name: fail2ban
    state: restarted
